// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// datGenC
SEXP datGenC(SEXP node, SEXP maxdeg, SEXP ordex, SEXP ts, SEXP noi, SEXP nobs, SEXP ivn, SEXP fX, SEXP beta);
RcppExport SEXP CDctnCpp_datGenC(SEXP nodeSEXP, SEXP maxdegSEXP, SEXP ordexSEXP, SEXP tsSEXP, SEXP noiSEXP, SEXP nobsSEXP, SEXP ivnSEXP, SEXP fXSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type maxdeg(maxdegSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ordex(ordexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type noi(noiSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ivn(ivnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fX(fXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP);
    __result = Rcpp::wrap(datGenC(node, maxdeg, ordex, ts, noi, nobs, ivn, fX, beta));
    return __result;
END_RCPP
}
// prodG
SEXP prodG(SEXP xnode, SEXP xlist, SEXP ylist, SEXP obslength);
RcppExport SEXP CDctnCpp_prodG(SEXP xnodeSEXP, SEXP xlistSEXP, SEXP ylistSEXP, SEXP obslengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type xnode(xnodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ylist(ylistSEXP);
    Rcpp::traits::input_parameter< SEXP >::type obslength(obslengthSEXP);
    __result = Rcpp::wrap(prodG(xnode, xlist, ylist, obslength));
    return __result;
END_RCPP
}
// gridCD
SEXP gridCD(SEXP node, SEXP beta, SEXP lambda, SEXP inprod, SEXP fprod, SEXP eorder, SEXP rsq, SEXP eps, SEXP coef, SEXP RSQ, SEXP ITER, SEXP nlam, SEXP sigma, SEXP sig, SEXP norm, SEXP obsleng, SEXP eorleng);
RcppExport SEXP CDctnCpp_gridCD(SEXP nodeSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP inprodSEXP, SEXP fprodSEXP, SEXP eorderSEXP, SEXP rsqSEXP, SEXP epsSEXP, SEXP coefSEXP, SEXP RSQSEXP, SEXP ITERSEXP, SEXP nlamSEXP, SEXP sigmaSEXP, SEXP sigSEXP, SEXP normSEXP, SEXP obslengSEXP, SEXP eorlengSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inprod(inprodSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fprod(fprodSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eorder(eorderSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rsq(rsqSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< SEXP >::type RSQ(RSQSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ITER(ITERSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nlam(nlamSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< SEXP >::type norm(normSEXP);
    Rcpp::traits::input_parameter< SEXP >::type obsleng(obslengSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eorleng(eorlengSEXP);
    __result = Rcpp::wrap(gridCD(node, beta, lambda, inprod, fprod, eorder, rsq, eps, coef, RSQ, ITER, nlam, sigma, sig, norm, obsleng, eorleng));
    return __result;
END_RCPP
}
