# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

datGenC <- function(node, maxdeg, ordex, ts, noi, nobs, ivn, fX, beta) {
    .Call('CDctnCpp_datGenC', PACKAGE = 'CDctnCpp', node, maxdeg, ordex, ts, noi, nobs, ivn, fX, beta)
}

prodG <- function(xnode, xlist, ylist, obslength) {
    .Call('CDctnCpp_prodG', PACKAGE = 'CDctnCpp', xnode, xlist, ylist, obslength)
}

gridCD <- function(node, beta, lambda, inprod, fprod, eorder, rsq, eps, coef, RSQ, ITER, nlam, sigma, sig, norm, obsleng, eorleng) {
    .Call('CDctnCpp_gridCD', PACKAGE = 'CDctnCpp', node, beta, lambda, inprod, fprod, eorder, rsq, eps, coef, RSQ, ITER, nlam, sigma, sig, norm, obsleng, eorleng)
}

